-- Audit service schema (owned by Flyway).

CREATE TABLE audit_log (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subject      VARCHAR(255) NOT NULL,
    event_type   VARCHAR(255) NOT NULL,
    source_topic VARCHAR(255) NOT NULL,
    details      TEXT NOT NULL,
    recorded_at  TIMESTAMP(6) WITH TIME ZONE NOT NULL
);

